/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.test.mavenproject4;

import com.google.gson.Gson;
import static com.test.mavenproject4.AgregarCliente.JSON;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

/**
 *
 * @author jezzvega
 */
public class Recepcion extends javax.swing.JFrame {
    
    private final OkHttpClient client = new OkHttpClient();
    public static final MediaType JSON = MediaType.get("application/json; charset=utf-8");
    
    Cliente clienteEnv, clienteRec;
    Double costoTotal = 0.00;
    Usuario user;
    double distancia = 0.00;
    int diasAproximados = 0;
    
    LatLng laVilla = new LatLng(7.9375927056531, -80.4140151416752);

    /**
     * Creates new form Recepcion
     */
    public Recepcion() {
        initComponents();
    }
    
    public Recepcion(Usuario user) {
        initComponents();
        this.user = user;
          URL iconURL = getClass().getResource("/ShippingPro2kiconr.png");
            // iconURL is null when not found
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        clientIdTxt = new javax.swing.JTextField();
        buscarClienteBtn = new javax.swing.JButton();
        verClienteBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        clientIdRecTxt = new javax.swing.JTextField();
        buscarClienteRecBtn = new javax.swing.JButton();
        verClienteRecBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        pesoTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descPaqueteTxt = new javax.swing.JTextArea();
        altaPriorCheck = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        distTxt = new javax.swing.JLabel();
        totalCostoTxt = new javax.swing.JLabel();
        calcTotalCost = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        diasAproxTxt = new javax.swing.JLabel();
        enviarEncomiendaBtn = new javax.swing.JButton();
        addClienteBtn = new javax.swing.JButton();
        encomiendasvBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel1.setText("Recepción de Encomiendas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REMITENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        jLabel2.setText("Cédula / RUC:");

        clientIdTxt.setToolTipText("");

        buscarClienteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_search_black_24dp.png"))); // NOI18N
        buscarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteBtnActionPerformed(evt);
            }
        });

        verClienteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_visibility_black_24dp.png"))); // NOI18N
        verClienteBtn.setEnabled(false);
        verClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verClienteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(clientIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(buscarClienteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(verClienteBtn)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscarClienteBtn)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clientIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(verClienteBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESTINATARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        jLabel6.setText("Cédula / RUC:");

        clientIdRecTxt.setToolTipText("");

        buscarClienteRecBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_search_black_24dp.png"))); // NOI18N
        buscarClienteRecBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteRecBtnActionPerformed(evt);
            }
        });

        verClienteRecBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_visibility_black_24dp.png"))); // NOI18N
        verClienteRecBtn.setEnabled(false);
        verClienteRecBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verClienteRecBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(clientIdRecTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(buscarClienteRecBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(verClienteRecBtn)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscarClienteRecBtn)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clientIdRecTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(verClienteRecBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DETALLES Y COSTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        pesoTxt.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        pesoTxt.setText("0.00");

        jLabel9.setText("Peso (lb):");

        jLabel10.setText("Descripción del Paquete:");

        descPaqueteTxt.setColumns(20);
        descPaqueteTxt.setLineWrap(true);
        descPaqueteTxt.setRows(4);
        jScrollPane2.setViewportView(descPaqueteTxt);

        altaPriorCheck.setText("Alta Prioridad:");
        altaPriorCheck.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        altaPriorCheck.setIconTextGap(65);
        altaPriorCheck.setMargin(new java.awt.Insets(1, 3, 0, 1));

        jLabel12.setText("Distancia:");

        distTxt.setText("0.00 km");

        totalCostoTxt.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        totalCostoTxt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        totalCostoTxt.setText("$0.00");

        calcTotalCost.setText("Calcular Total");
        calcTotalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcTotalCostActionPerformed(evt);
            }
        });

        jLabel13.setText("Tiempo Estimando:");

        diasAproxTxt.setText("0 dia(s)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(altaPriorCheck)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(93, 93, 93)
                                .addComponent(pesoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(distTxt)
                                    .addComponent(diasAproxTxt))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calcTotalCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalCostoTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(calcTotalCost)
                    .addComponent(distTxt))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 10, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(diasAproxTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(altaPriorCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(pesoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalCostoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        enviarEncomiendaBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        enviarEncomiendaBtn.setText("Registrar Encomienda");
        enviarEncomiendaBtn.setEnabled(false);
        enviarEncomiendaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarEncomiendaBtnActionPerformed(evt);
            }
        });

        addClienteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_add_black_24dp.png"))); // NOI18N
        addClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClienteBtnActionPerformed(evt);
            }
        });

        encomiendasvBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        encomiendasvBTN.setText("Ver Encomiendas");
        encomiendasvBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encomiendasvBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addClienteBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(encomiendasvBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enviarEncomiendaBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addClienteBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enviarEncomiendaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(encomiendasvBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buscarClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteBtnActionPerformed

        String clientId = clientIdTxt.getText();
        
        buscarClienteBtn.setEnabled(false);
        verClienteBtn.setEnabled(false);
        //limpiarCampos("Env");
        
        try {
            buscarCliente(clientId, "Env");
        } catch (Exception ex) {
            Logger.getLogger(Recepcion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_buscarClienteBtnActionPerformed

    private void verClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verClienteBtnActionPerformed
        
        String clienteData = "Nombre: " + clienteEnv.getNombre()
                + "\nTelefono: " + clienteEnv.getTelefono()
                + "\nUbicacion: " + clienteEnv.getUbicacion_desc();
        
        JOptionPane.showMessageDialog(
                                null,
                                clienteData, 
                                "Cliente",
                                JOptionPane.PLAIN_MESSAGE
                        );
    }//GEN-LAST:event_verClienteBtnActionPerformed

    private void buscarClienteRecBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteRecBtnActionPerformed
        
        String clientId = clientIdRecTxt.getText();
        
        buscarClienteRecBtn.setEnabled(false);
        verClienteRecBtn.setEnabled(false);
        //limpiarCampos("Rec");
        
        try {
            buscarCliente(clientId, "Rec");
        } catch (Exception ex) {
            Logger.getLogger(Recepcion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarClienteRecBtnActionPerformed

    private void verClienteRecBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verClienteRecBtnActionPerformed
        
        String clienteData = "Nombre: " + clienteRec.getNombre()
                + "\nTelefono: " + clienteRec.getTelefono()
                + "\nUbicacion: " + clienteRec.getUbicacion_desc();
        
        JOptionPane.showMessageDialog(
                                null,
                                clienteData, 
                                "Cliente",
                                JOptionPane.PLAIN_MESSAGE
                        );
    }//GEN-LAST:event_verClienteRecBtnActionPerformed

    private void addClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClienteBtnActionPerformed
        AgregarCliente addCli = new AgregarCliente(user);
        addCli.setVisible(true);
    }//GEN-LAST:event_addClienteBtnActionPerformed

    private void calcTotalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcTotalCostActionPerformed
        
        costoTotal = 0.00;
        String peso = pesoTxt.getText();
        
        if(peso.isBlank() || Double.parseDouble(peso) <= 0.00){
            
            JOptionPane.showMessageDialog(
                                null,
                                "Introduza un peso válido.", 
                                "",
                                JOptionPane.ERROR_MESSAGE
                        );
            
            return;
            
        }
        
        costoTotal += distancia * 0.35;
        costoTotal += Double.parseDouble(peso) * 0.45;
        
        if(altaPriorCheck.isSelected()){
            costoTotal += 10.00;
        }
        
        diasAproximados = calcDiasAprox(distancia, altaPriorCheck.isSelected());
        
        diasAproxTxt.setText(String.format("%d dia(s)", diasAproximados));
        
        totalCostoTxt.setText(String.format("$%.2f", costoTotal));
        
        if(costoTotal > 0) enviarEncomiendaBtn.setEnabled(true);
        
    }//GEN-LAST:event_calcTotalCostActionPerformed
    
    private int calcDiasAprox(Double dist, boolean altaPrioridad){
        
        int diasAprox = 0;
        
        if(altaPrioridad){
            if(dist <= 300){
                diasAprox = 1;
            }else{
                diasAprox = 2;
            }
        }else{
            if(dist <= 100){
                diasAprox = 3;
            }else if(dist <= 300){
                diasAprox = 5;
            }else{
                diasAprox = 7;
            }
        }
        
        return diasAprox;
        
    }
    
    private void enviarEncomiendaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarEncomiendaBtnActionPerformed
        
        String descPaquete = descPaqueteTxt.getText();
        double peso = Double.parseDouble(pesoTxt.getText());
        
        if(descPaquete.isBlank()){
            JOptionPane.showMessageDialog(
                                null,
                                "Debe introducir una descripción del paquete.", 
                                "Ha ocurrido un problema",
                                JOptionPane.ERROR_MESSAGE
                        );
            
            return;
        }
        
        enviarEncomiendaBtn.setEnabled(false);
        
        String json = "{\n" +
                        "    \"envia\": \"" + clienteEnv.getId() + "\",\n" +
                        "    \"recibe\": \"" + clienteRec.getId() + "\",\n" +
                        "    \"prioridad\": " + (altaPriorCheck.isSelected() ? 1 : 0) + ",\n" +
                        "    \"peso\": " + peso + ",\n" +
                        "    \"costo\": " + costoTotal + ",\n" +
                        "    \"tiempo_envio\": " + diasAproximados + ",\n" +
                        "    \"descripcion\": \"" + descPaquete + "\"\n" +
                        "}";
        
        RequestBody body = RequestBody.create(JSON, json);
        
        Request request = new Request.Builder()
            .url("https://t-express-rest.herokuapp.com/encomiendas/agregar")
            .header("auth-token", user.getToken())
            .post(body)
            .build();
        
        client.newCall(request).enqueue(new Callback(){
            @Override
            public void onFailure(Call call, IOException ioe) {
                System.out.println(ioe.getMessage());
            }

            @Override
            public void onResponse(Call call, Response res) throws IOException {
                
                Object[] options = {"OK"};
                
                if(!res.isSuccessful()){
                    
                    JOptionPane.showOptionDialog(
                                null,
                                res.body().string(), 
                                "Ha ocurrido un problema",
                                JOptionPane.OK_OPTION,
                                JOptionPane.ERROR_MESSAGE,
                                null, options, options[0]
                            );
                    
                    enviarEncomiendaBtn.setEnabled(true);
                    return;
                }
                
                int dialogRes = JOptionPane.showOptionDialog(
                                null,
                                "La encomienda se ha guardado correctamente!", 
                                "Encomienda Guardada",
                                JOptionPane.OK_OPTION,
                                JOptionPane.INFORMATION_MESSAGE,
                                null, options, options[0]
                        );
                
                if(dialogRes == JOptionPane.OK_OPTION){
                    limpiarCampos();
                }
                
            }
            
        });
        
    }//GEN-LAST:event_enviarEncomiendaBtnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
      Autenticacion a = new Autenticacion();
     a.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void encomiendasvBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encomiendasvBTNActionPerformed
       Encomiendas_View e = new Encomiendas_View(user);
       e.setVisible(true);
    }//GEN-LAST:event_encomiendasvBTNActionPerformed

    public void buscarCliente(String id, String tipo) throws Exception {
        
        if(id.isBlank()) {
            JOptionPane.showMessageDialog(
                                null,
                                "Debe introducir el " + (tipo.equals("Env") ? "Emisor" : "Receptor"), 
                                "Ha ocurrido un problema",
                                JOptionPane.ERROR_MESSAGE
                        );
            return;
        }
        
        Request request = new Request.Builder()
                .url("https://t-express-rest.herokuapp.com/clientes/" + id)
                .header("auth-token", user.getToken())
                .build();
        
        client.newCall(request).enqueue(new Callback(){
            @Override
            public void onFailure(Call call, IOException ioe) {
            }

            @Override
            public void onResponse(Call call, Response res) throws IOException {
                
                try (ResponseBody responseBody = res.body()) {
                    
                    String json = responseBody.string();
                    
                    if (!res.isSuccessful()) {
                        
                        JOptionPane.showMessageDialog(
                                null,
                                json, 
                                "Ha ocurrido un problema",
                                JOptionPane.ERROR_MESSAGE
                        );
                        
                        buscarClienteBtn.setEnabled(true);
                        buscarClienteRecBtn.setEnabled(true);
                        
                        responseBody.close();
                        
                        return;
                        
                    }
                    
                    if(tipo.equals("Env")){
                        clienteEnv = new Gson().fromJson(json, Cliente.class);
                        
                        buscarClienteBtn.setEnabled(true);

                        verClienteBtn.setEnabled(true);
                        
                        responseBody.close();
                        
                    }else{
                        clienteRec = new Gson().fromJson(json, Cliente.class);
                        
                        //Se calcula la distancia
                        distancia = laVilla.distanceTo(clienteRec.getUbic_lat(), clienteRec.getUbic_long());
                        
                        distTxt.setText(String.format("%.2f km", distancia));
                        
                        buscarClienteRecBtn.setEnabled(true);

                        verClienteRecBtn.setEnabled(true);
                        
                        responseBody.close();
                    }
                }
            }
            
        });
        
    }
    
    private void limpiarCampos(){
        
        clienteEnv = null;
        clienteRec = null;
        
        clientIdTxt.setText(null);
        clientIdRecTxt.setText(null);
        
        verClienteBtn.setEnabled(false);
        verClienteRecBtn.setEnabled(false);
        
        descPaqueteTxt.setText(null);
        
        distTxt.setText("0.00 km");
        
        diasAproxTxt.setText("0 dia(s)");
        
        altaPriorCheck.setSelected(false);
        
        pesoTxt.setText("0.00");
        
        totalCostoTxt.setText("$0.00");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recepcion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClienteBtn;
    private javax.swing.JCheckBox altaPriorCheck;
    private javax.swing.JButton buscarClienteBtn;
    private javax.swing.JButton buscarClienteRecBtn;
    private javax.swing.JButton calcTotalCost;
    private javax.swing.JTextField clientIdRecTxt;
    private javax.swing.JTextField clientIdTxt;
    private javax.swing.JTextArea descPaqueteTxt;
    private javax.swing.JLabel diasAproxTxt;
    private javax.swing.JLabel distTxt;
    private javax.swing.JButton encomiendasvBTN;
    private javax.swing.JButton enviarEncomiendaBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField pesoTxt;
    private javax.swing.JLabel totalCostoTxt;
    private javax.swing.JButton verClienteBtn;
    private javax.swing.JButton verClienteRecBtn;
    // End of variables declaration//GEN-END:variables
}
