//LINEA 657 COMENTADA POR ERROR

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.test.mavenproject4;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import static com.test.mavenproject4.Recepcion.JSON;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

/**
 *
 * @author jcs98
 */
public class VistaAdministrador extends javax.swing.JFrame {

    private final OkHttpClient client = new OkHttpClient();
    public static final MediaType JSON = MediaType.get("application/json; charset=utf-8");
    private Usuario user;
    private List<String> filtros = new ArrayList<>();
    private List<String> ordenarPor = new ArrayList<>();
    List<Encomiendas> encomiendas;

    public VistaAdministrador() {
        initComponents();
    }

    public VistaAdministrador(Usuario user) {
        initComponents();
        this.user = user;

        loadAdminDashboard();

        //Se inicializan los filtros
        filtros.add("estado in(0, 1, 2)");
        filtros.add("estado = 0");
        filtros.add("estado = 1");
        filtros.add("estado = 2");
        filtros.add("prioridad = 1");
        filtros.add("prioridad = 0");

        //Se inicializan los ordenar
        ordenarPor.add("fecha_entrada desc");
        ordenarPor.add("fecha_entrada asc");
        ordenarPor.add("estado");
        ordenarPor.add("prioridad");
        ordenarPor.add("c1.nombre");
        ordenarPor.add("c2.nombre");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        panelAdmin = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        vehicDispLb = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        enProcesoLb = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        recibidasLb = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        enviadasLb = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vistaGeneralJTable = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ingresoMonetarioLb = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        encomiendasJTable = new javax.swing.JTable();
        jPanel21 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        filtroPorCBox = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        ordenPorCBox = new javax.swing.JComboBox<>();
        jPanel22 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ingresoFiltradoLb = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel24 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel25 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel27 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jPanel28 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel30 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jPanel31 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PANEL DE ADMINISTRADOR");
        setResizable(false);

        panelAdmin.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        panelAdmin.setToolTipText("");
        panelAdmin.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        panelAdmin.setName("Recibo de paquetes\nEnvío de paquetes\nAdministrar clientes\nAdministrar repartidores\nAdministrar vehículos"); // NOI18N
        panelAdmin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                panelAdminStateChanged(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VISTA GENERAL (ÚLTIMOS 30 DÍAS) ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 14))); // NOI18N
        jPanel2.setName(""); // NOI18N

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1.setText("Vehículos disponibles");

        vehicDispLb.setFont(new java.awt.Font("Montserrat Black", 1, 18)); // NOI18N
        vehicDispLb.setText("0/0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicDispLb, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vehicDispLb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel4.setText("En Camino");

        enProcesoLb.setFont(new java.awt.Font("Montserrat Black", 1, 18)); // NOI18N
        enProcesoLb.setForeground(new java.awt.Color(0, 153, 0));
        enProcesoLb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        enProcesoLb.setText("0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 173, Short.MAX_VALUE))
                    .addComponent(enProcesoLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enProcesoLb)
                .addContainerGap())
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel19.setText("Recibidas");

        recibidasLb.setFont(new java.awt.Font("Montserrat Black", 1, 18)); // NOI18N
        recibidasLb.setForeground(new java.awt.Color(204, 0, 0));
        recibidasLb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        recibidasLb.setText("0");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(0, 182, Short.MAX_VALUE))
                    .addComponent(recibidasLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(recibidasLb)
                .addContainerGap())
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel21.setText("Entregadas");

        enviadasLb.setFont(new java.awt.Font("Montserrat Black", 1, 18)); // NOI18N
        enviadasLb.setForeground(new java.awt.Color(204, 0, 0));
        enviadasLb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        enviadasLb.setText("0");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enviadasLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 171, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enviadasLb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ÚLTIMAS 10 ENCOMIENDAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 14))); // NOI18N

        vistaGeneralJTable.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        vistaGeneralJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "EMISOR", "RECEPTOR", "ESTADO", "FECHA DE REGISTRO", "COSTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(vistaGeneralJTable);
        if (vistaGeneralJTable.getColumnModel().getColumnCount() > 0) {
            vistaGeneralJTable.getColumnModel().getColumn(0).setResizable(false);
            vistaGeneralJTable.getColumnModel().getColumn(1).setResizable(false);
            vistaGeneralJTable.getColumnModel().getColumn(2).setResizable(false);
            vistaGeneralJTable.getColumnModel().getColumn(3).setResizable(false);
            vistaGeneralJTable.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel6.setText("Ingreso Monetario");

        ingresoMonetarioLb.setFont(new java.awt.Font("Montserrat Black", 1, 18)); // NOI18N
        ingresoMonetarioLb.setForeground(new java.awt.Color(0, 153, 0));
        ingresoMonetarioLb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ingresoMonetarioLb.setText("0.00");

        jLabel24.setFont(new java.awt.Font("Montserrat Black", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 153, 0));
        jLabel24.setText("$");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingresoMonetarioLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(ingresoMonetarioLb))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelAdmin.addTab("VISTA GENERAL", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de encomiendas"));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        encomiendasJTable.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        encomiendasJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "EMISOR", "RECEPTOR", "ESTADO", "PRIORIDAD", "FECHA RECIBIDO", "TIEMPO ESTIMADO", "COSTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(encomiendasJTable);
        if (encomiendasJTable.getColumnModel().getColumnCount() > 0) {
            encomiendasJTable.getColumnModel().getColumn(0).setResizable(false);
            encomiendasJTable.getColumnModel().getColumn(1).setResizable(false);
            encomiendasJTable.getColumnModel().getColumn(2).setResizable(false);
            encomiendasJTable.getColumnModel().getColumn(3).setResizable(false);
            encomiendasJTable.getColumnModel().getColumn(4).setResizable(false);
            encomiendasJTable.getColumnModel().getColumn(5).setResizable(false);
            encomiendasJTable.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel20.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 680, 370));

        jPanel3.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 710, 400));

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder("Controles"));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Filtrar por:");
        jPanel21.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        filtroPorCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos (por defecto)", "Recibidas", "En Camino", "Entregadas", "Alta Prioridad", "Baja Prioridad" }));
        jPanel21.add(filtroPorCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 140, -1));

        jLabel26.setText("Ordenar por:");
        jPanel21.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        ordenPorCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recientes (por defecto)", "Antiguos", "Estado", "Prioridad", "Emisor", "Receptor" }));
        jPanel21.add(ordenPorCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 140, -1));

        jPanel3.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 60));

        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("Eliminar");
        jButton4.setToolTipText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel22.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, -1));

        jPanel3.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 200, 60));

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, -1, -1));

        ingresoFiltradoLb.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        ingresoFiltradoLb.setText("$0.00");
        jPanel3.add(ingresoFiltradoLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        panelAdmin.addTab("ENCOMIENDAS", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de encomiendas"));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel23.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 680, 370));

        jPanel4.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 710, 400));

        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder("Controles"));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setText("Filtrar por:");
        jPanel24.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel24.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 140, -1));

        jLabel31.setText("Ordenar por:");
        jPanel24.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel24.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 140, -1));

        jPanel4.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 60));

        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("Modificar");
        jButton5.setToolTipText("Modificar");
        jPanel25.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, -1));

        jButton6.setText("Eliminar");
        jButton6.setToolTipText("Eliminar");
        jPanel25.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 70, -1));

        jPanel4.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 200, 60));

        panelAdmin.addTab("CLIENTES", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de encomiendas"));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel26.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 680, 370));

        jPanel5.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 710, 400));

        jPanel27.setBorder(javax.swing.BorderFactory.createTitledBorder("Controles"));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setText("Filtrar por:");
        jPanel27.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel27.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 140, -1));

        jLabel33.setText("Ordenar por:");
        jPanel27.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel27.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 140, -1));

        jPanel5.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 60));

        jPanel28.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setText("Modificar");
        jButton7.setToolTipText("Modificar");
        jPanel28.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, -1));

        jButton8.setText("Eliminar");
        jButton8.setToolTipText("Eliminar");
        jPanel28.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 70, -1));

        jPanel5.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 200, 60));

        panelAdmin.addTab("REPARTIDORES", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel29.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de encomiendas"));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jPanel29.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 680, 370));

        jPanel6.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 710, 400));

        jPanel30.setBorder(javax.swing.BorderFactory.createTitledBorder("Controles"));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setText("Filtrar por:");
        jPanel30.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel30.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 140, -1));

        jLabel35.setText("Ordenar por:");
        jPanel30.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel30.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 140, -1));

        jPanel6.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 60));

        jPanel31.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setText("Modificar");
        jButton9.setToolTipText("Modificar");
        jPanel31.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, -1));

        jButton10.setText("Eliminar");
        jButton10.setToolTipText("Eliminar");
        jPanel31.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 70, -1));

        jPanel6.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 200, 60));

        panelAdmin.addTab("VEHÍCULOS", jPanel6);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        panelAdmin.addTab("tab6", jPanel9);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAdmin)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelAdmin)
                .addContainerGap())
        );

        panelAdmin.getAccessibleContext().setAccessibleName("Envío de paquetes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelAdminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_panelAdminStateChanged
        JTabbedPane menu = (JTabbedPane) evt.getSource();

        int selectedTab = menu.getSelectedIndex();

        switch (selectedTab) {
            case 0:
                if (user != null) {
                    loadAdminDashboard();
                }
                break;
            case 1:
                loadEncomiendas();
                break;
            case 2:
                loadClientes();
                break;
            case 3:
                loadRepartidores();
                break;
            case 4:
                loadVehiculos();
                break;
        }
    }//GEN-LAST:event_panelAdminStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        loadEncomiendas();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Object[] options = {"Borrar", "Cancelar"};

        int dialogRes = JOptionPane.showOptionDialog(
                null,
                "La encomienda se borrará, esta accion no puede ser revertida.\n\n¿Desea Continuar?",
                "Borrar Encomienda",
                JOptionPane.OK_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]
        );

        if (dialogRes == JOptionPane.OK_OPTION) {

            int selectedRow = encomiendasJTable.getSelectedRow();

            Encomiendas encomienda = encomiendas.get(selectedRow);

            int encomiendaId = encomienda.getId();

            String json = "{\n"
                    + "    \"id\": " + encomiendaId + "\n"
                    + "}";

            RequestBody body = RequestBody.create(JSON, json);

            Request request = new Request.Builder()
                    //.url("https://t-express-rest.herokuapp.com/encomiendas/eliminar")
                    .url("http://localhost:3000/encomiendas/eliminar")
                    .header("auth-token", user.getToken())
                    .delete(body)
                    .build();

            client.newCall(request).enqueue(new Callback() {
                @Override
                public void onFailure(Call call, IOException ioe) {
                    System.out.println(ioe.getMessage());
                }

                @Override
                public void onResponse(Call call, Response rspns) throws IOException {

                    try ( ResponseBody responseBody = rspns.body()) {
                        String json = responseBody.string();

                        if (!rspns.isSuccessful()) {

                            JOptionPane.showMessageDialog(
                                    null,
                                    json,
                                    "Ha ocurrido un problema",
                                    JOptionPane.ERROR_MESSAGE
                            );

                            responseBody.close();

                            return;

                        }

                        JOptionPane.showMessageDialog(
                                null,
                                json,
                                "Eliminada",
                                JOptionPane.INFORMATION_MESSAGE
                        );

                        responseBody.close();

                        loadEncomiendas();

                    }
                }
            });

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info.getName());
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel enProcesoLb;
    private javax.swing.JTable encomiendasJTable;
    private javax.swing.JLabel enviadasLb;
    private javax.swing.JComboBox<String> filtroPorCBox;
    private javax.swing.JLabel ingresoFiltradoLb;
    private javax.swing.JLabel ingresoMonetarioLb;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> ordenPorCBox;
    private javax.swing.JTabbedPane panelAdmin;
    private javax.swing.JLabel recibidasLb;
    private javax.swing.JLabel vehicDispLb;
    private javax.swing.JTable vistaGeneralJTable;
    // End of variables declaration//GEN-END:variables

    private void loadAdminDashboard() {

        Request request = new Request.Builder()
                //.url("https://t-express-rest.herokuapp.com/encomiendas/")
                .url("http://localhost:3000/encomiendas/adminPanel")
                .header("auth-token", user.getToken())
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException ioe) {
                System.out.println(ioe.getMessage());
            }

            @Override
            public void onResponse(Call call, Response rspns) throws IOException {

                try ( ResponseBody responseBody = rspns.body()) {
                    String json = responseBody.string();

                    if (!rspns.isSuccessful()) {

                        JOptionPane.showMessageDialog(
                                null,
                                json,
                                "Ha ocurrido un problema",
                                JOptionPane.ERROR_MESSAGE
                        );

                        responseBody.close();

                        return;

                    }

                    AdminDashboardData adminData = new Gson().fromJson(json, AdminDashboardData.class);

                    ingresoMonetarioLb.setText(String.format("%.2f", adminData.getIngreso()));

                    recibidasLb.setText("" + adminData.getRecibidas());
                    enProcesoLb.setText("" + adminData.getEn_camino());
                    enviadasLb.setText("" + adminData.getEntregadas());

                    vehicDispLb.setText(String.format("%d/%d", adminData.getVehiculos_disponibles(), adminData.getVehiculos_totales()));

                    int index = 0;

                    for (Encomiendas encomienda : adminData.getUltimasEncomiendas()) {

                        vistaGeneralJTable.getModel().setValueAt(encomienda.getEnvia(), index, 0);
                        vistaGeneralJTable.getModel().setValueAt(encomienda.getRecibe(), index, 1);
                        vistaGeneralJTable.getModel().setValueAt(encomienda.getEstadoText(), index, 2);
                        vistaGeneralJTable.getModel().setValueAt(encomienda.getFecha_de_entrada(), index, 3);
                        vistaGeneralJTable.getModel().setValueAt(String.format("%.2f", encomienda.getCosto()), index, 4);

                        index++;
                    }

                    responseBody.close();

                }
            }
        });

    }

    private void loadEncomiendas() {

        int selectedFiltro = filtroPorCBox.getSelectedIndex();
        int selectedOrden = ordenPorCBox.getSelectedIndex();

        String queryParams = "?filtro=" + filtros.get(selectedFiltro) + "&orden=" + ordenarPor.get(selectedOrden);

        Request request = new Request.Builder()
                //.url("https://t-express-rest.herokuapp.com/encomiendas/"+queryParams)
                .url("http://localhost:3000/encomiendas/" + queryParams)
                .header("auth-token", user.getToken())
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException ioe) {
                System.out.println(ioe.getMessage());
            }

            @Override
            public void onResponse(Call call, Response rspns) throws IOException {

                Double ingresoFiltrado = 0.00;

                try ( ResponseBody responseBody = rspns.body()) {
                    String json = responseBody.string();

                    if (!rspns.isSuccessful()) {

                        JOptionPane.showMessageDialog(
                                null,
                                json,
                                "Ha ocurrido un problema",
                                JOptionPane.ERROR_MESSAGE
                        );

                        responseBody.close();

                        return;

                    }

                    encomiendas = new Gson().fromJson(json, new TypeToken<List<Encomiendas>>() {
                    }.getType());

                    DefaultTableModel dtm = (DefaultTableModel) encomiendasJTable.getModel();

                    dtm.setRowCount(encomiendas.size());

                    int index = 0;

                    for (Encomiendas encomienda : encomiendas) {

                        encomiendasJTable.getModel().setValueAt(encomienda.getEnvia(), index, 0);
                        encomiendasJTable.getModel().setValueAt(encomienda.getRecibe(), index, 1);
                        encomiendasJTable.getModel().setValueAt(encomienda.getEstadoText(), index, 2);
                        encomiendasJTable.getModel().setValueAt(encomienda.getPrioridadText(), index, 3);
                        encomiendasJTable.getModel().setValueAt(encomienda.getFecha_de_entrada(), index, 4);
                        encomiendasJTable.getModel().setValueAt(encomienda.getTiempoEstTxt(), index, 5);
                        encomiendasJTable.getModel().setValueAt(String.format("%.2f", encomienda.getCosto()), index, 6);

                        ingresoFiltrado += encomienda.getCosto();

                        index++;
                    }

                    ingresoFiltradoLb.setText(String.format("$%.2f", ingresoFiltrado));

                    responseBody.close();

                }
            }
        });
    }

    private void loadClientes() {

    }

    private void loadRepartidores() {

    }

    private void loadVehiculos() {

    }
}
